config/routes.rb
Byglass::Application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :sales

  resources :graphics

  resources :categories

  resources :projects

  resources :measures

  resources :shapes

  resources :hardwares

  resources :glasses

  resources :dimensions

  resources :types

  resources :products

  resources :customers

  get "pages/about"
  get "pages/contact"
  get "home/index"

  root to: "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :projects
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :states, foreign_key: 'state_id'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

	has_many :sale

	validates_presence_of :name
	validates_format_of :email, with: EMAIL_REGEXP, uniqueness: true
end

app/models/glass.rb
class Glass < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/graphic.rb
class Graphic < ActiveRecord::Base
end

app/models/hardware.rb
class Hardware < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/measure.rb
class Measure < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :type
end

app/models/products_sales.rb
class ProductsSales < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :categories
	has_and_belongs_to_many :hardwares
	has_and_belongs_to_many :measures
	has_and_belongs_to_many :glasses
	has_and_belongs_to_many :shapes	

	validates_presence_of :title, :code, :category_id
	validates_length_of :description, minimum: 10, maximum: 600, allow_blank: false
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :customer
	belongs_to :user
	has_and_belongs_to_many :product
	validates_presence_of :customer_id, :value, :payment_method
end

app/models/shape.rb
class Shape < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :cities
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, stretches: 20
	has_many :sale
end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
  before_action :set_shape, only: [:show, :edit, :update, :destroy]

  # GET /shapes
  # GET /shapes.json
  def index
    @shapes = Shape.all
  end

  # GET /shapes/1
  # GET /shapes/1.json
  def show
  end

  # GET /shapes/new
  def new
    @shape = Shape.new
  end

  # GET /shapes/1/edit
  def edit
  end

  # POST /shapes
  # POST /shapes.json
  def create
    @shape = Shape.new(shape_params)

    respond_to do |format|
      if @shape.save
        format.html { redirect_to @shape, notice: 'Shape was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shape }
      else
        format.html { render action: 'new' }
        format.json { render json: @shape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shapes/1
  # PATCH/PUT /shapes/1.json
  def update
    respond_to do |format|
      if @shape.update(shape_params)
        format.html { redirect_to @shape, notice: 'Shape was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shapes/1
  # DELETE /shapes/1.json
  def destroy
    @shape.destroy
    respond_to do |format|
      format.html { redirect_to shapes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shape
      @shape = Shape.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shape_params
      params.require(:shape).permit(:type, :cost, :markup, :value)
    end
end

app/helpers/glasses_helper.rb
module GlassesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
	def which_method(method)
		case method
		when 1
			return "Cartão de crédito"
		when 2
			return "Cartão de débito"
		when 3
			return "Dinheiro"
		when 4
			return "Cheque"			
		end
	end

	def is_payed(value)
		case value
		when true
			return "Pago!"
		when false
			return "Não pago."
		end
	end

	def is_delivered(value)
		case value
		when true
			return "Entregue!"
		when false
			return "Não entregue."
		end
	end

	def user_name(user)
		if user.present?
			user.name
		end
	end
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shapes/_form.html.erb
<div class="row">
<%= bootstrap_form_for(@shape) do |f| %>
  <% if @shape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shape.errors.count, "error") %> prohibited this shape from being saved:</h2>

      <ul>
      <% @shape.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group col-md-6 col-sm-12 col-xs-12">
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="control-group col-md-6 col-sm-12 col-xs-12">    
      <%= f.number_field :cost, prepend: 'R$ ' %>
  </div>
  <div class="control-group col-md-6 col-sm-12 col-xs-12">
    <%= f.text_field :markup, class: 'form-control', append: '%' %>
  </div>
  <div class="control-group col-md-6 col-sm-12 col-xs-12">
    <%= f.text_field :value, class: 'form-control', prepend: 'R$ ' %>
  </div>
  <div class="control-group col-md-12">
    <br>
    <%= f.submit class: 'btn btn-primary pull-right' %>
  </div>
<% end %>
</div>

app/views/shapes/edit.html.erb
<h1>Editing shape</h1>

<%= render 'form' %>

<%= link_to 'Show', @shape %> |
<%= link_to 'Back', shapes_path %>

app/views/shapes/index.html.erb
<h1><%= t('.page_title') %></h1>

<%= link_to new_shape_path, class: 'btn btn-primary pull-right' do %>
<i class="glyphicon glyphicon-plus"></i> <%= t('links.new') %>
<% end %>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t('.title') %></th>
      <th><%= t('.cost') %></th>
      <th><%= t('.markup') %></th>
      <th><%= t('.value') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shapes.each do |shape| %>
      <tr>
        <td><%= shape.title %></td>
        <td><%= shape.cost %></td>
        <td><%= shape.markup %></td>
        <td><%= shape.value %></td>
        <td><%= link_to 'Show', shape %></td>
        <td><%= link_to 'Edit', edit_shape_path(shape) %></td>
        <td><%= link_to 'Destroy', shape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/shapes/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), shapes_path %>

app/views/shapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @shape.title %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @shape.cost %>
</p>

<p>
  <strong>Markup:</strong>
  <%= @shape.markup %>
</p>

<p>
  <strong>Value:</strong>
  <%= @shape.value %>
</p>

<%= link_to 'Edit', edit_shape_path(@shape) %> |
<%= link_to 'Back', shapes_path %>