config/routes.rb
Byglass::Application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :sales

  resources :graphics

  resources :categories

  resources :projects

  resources :measures

  resources :shapes

  resources :hardwares

  resources :glasses

  resources :dimensions

  resources :types

  resources :products

  resources :customers

  get "pages/about"
  get "pages/contact"
  get "home/index"

  root to: "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :projects
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :states, foreign_key: 'state_id'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

	has_many :sale

	validates_presence_of :name
	validates_format_of :email, with: EMAIL_REGEXP, uniqueness: true
end

app/models/glass.rb
class Glass < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/graphic.rb
class Graphic < ActiveRecord::Base
end

app/models/hardware.rb
class Hardware < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/measure.rb
class Measure < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :type
end

app/models/products_sales.rb
class ProductsSales < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :categories
	has_and_belongs_to_many :hardwares
	has_and_belongs_to_many :measures
	has_and_belongs_to_many :glasses
	has_and_belongs_to_many :shapes	

	validates_presence_of :title, :code, :category_id
	validates_length_of :description, minimum: 10, maximum: 600, allow_blank: false
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :customer
	belongs_to :user
	has_and_belongs_to_many :product
	validates_presence_of :customer_id, :value, :payment_method
end

app/models/shape.rb
class Shape < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :cities
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, stretches: 20
	has_many :sale
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    @categories = Category.all
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :code, :category_id, :description)
    end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
	def which_method(method)
		case method
		when 1
			return "Cartão de crédito"
		when 2
			return "Cartão de débito"
		when 3
			return "Dinheiro"
		when 4
			return "Cheque"			
		end
	end

	def is_payed(value)
		case value
		when true
			return "Pago!"
		when false
			return "Não pago."
		end
	end

	def is_delivered(value)
		case value
		when true
			return "Entregue!"
		when false
			return "Não entregue."
		end
	end

	def user_name(user)
		if user.present?
			user.name
		end
	end
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/projects/_form.html.erb
<div class="row">
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, t('general.error') ) %> <%= t('general.form_error') %></h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br>
    <%= collection_select(:project, :category_id, Category.all, :id, :title, :prompt => t('general.select')) %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1><%= t('.page_title') %></h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t('.title') %></th>
      <th><%= t('.code') %></th>
      <th><%= t('.category') %></th>
      <th><%= t('.description') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= t(project.title) %></td>
        <td><%= project.code %></td>
        <td><%= project.category_id %></td>
        <td><%= project.description %></td>
        <td><%= link_to t('links.view'), project, class: 'btn btn-xs btn-primary' %></td>
        <td><%= link_to t('links.edit'), edit_project_path(project), class: 'btn btn-xs btn-success' %></td>
        <td><%= link_to t('links.delete'), project, class: 'btn btn-xs btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('links.new'), new_project_path, :class => 'btn btn-primary' %>

app/views/projects/new.html.erb
<h1><%= t 'projects.new.title' %></h1>

<%= render 'form' %>

<%= link_to t('links.back'), projects_path, :class => 'btn btn-xs btn-primary' %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Code:</strong>
  <%= @project.code %>
</p>

<p>
  <strong>Category:</strong>
  <%= @project.category_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>