config/routes.rb
Byglass::Application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :sales

  resources :graphics

  resources :categories

  resources :projects

  resources :measures

  resources :shapes

  resources :hardwares

  resources :glasses

  resources :dimensions

  resources :types

  resources :products

  resources :customers

  get "pages/about"
  get "pages/contact"
  get "home/index"

  root to: "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :projects
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :states, foreign_key: 'state_id'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

	has_many :sale

	validates_presence_of :name
	validates_format_of :email, with: EMAIL_REGEXP, uniqueness: true
end

app/models/glass.rb
class Glass < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/graphic.rb
class Graphic < ActiveRecord::Base
end

app/models/hardware.rb
class Hardware < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/measure.rb
class Measure < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :type
end

app/models/products_sales.rb
class ProductsSales < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :categories
	has_and_belongs_to_many :hardwares
	has_and_belongs_to_many :measures
	has_and_belongs_to_many :glasses
	has_and_belongs_to_many :shapes	

	validates_presence_of :title, :code, :category_id
	validates_length_of :description, minimum: 10, maximum: 600, allow_blank: false
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :customer
	belongs_to :user
	has_and_belongs_to_many :product
	validates_presence_of :customer_id, :value, :payment_method
end

app/models/shape.rb
class Shape < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :cities
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, stretches: 20
	has_many :sale
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
	def which_method(method)
		case method
		when 1
			return "Cartão de crédito"
		when 2
			return "Cartão de débito"
		when 3
			return "Dinheiro"
		when 4
			return "Cheque"			
		end
	end

	def is_payed(value)
		case value
		when true
			return "Pago!"
		when false
			return "Não pago."
		end
	end

	def is_delivered(value)
		case value
		when true
			return "Entregue!"
		when false
			return "Não entregue."
		end
	end

	def user_name(user)
		if user.present?
			user.name
		end
	end
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= bootstrap_form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.description %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title</strong>
  <%= @category.title %>
</p>

<p>
  <strong>Description</strong>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>