config/routes.rb
Byglass::Application.routes.draw do
  devise_for :users, controllers: { sessions: "users/sessions" }

  resources :sales

  resources :graphics

  resources :categories

  resources :projects

  resources :measures

  resources :shapes

  resources :hardwares

  resources :glasses

  resources :dimensions

  resources :types

  resources :products

  resources :customers

  get "pages/about"
  get "pages/contact"
  get "home/index"

  root to: "home#index"

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :projects
end

app/models/city.rb
class City < ActiveRecord::Base
	belongs_to :states, foreign_key: 'state_id'
end

app/models/customer.rb
class Customer < ActiveRecord::Base
	EMAIL_REGEXP = /\A[^@]+@([^@\.]+\.)+[^@\.]+\z/

	has_many :sale

	validates_presence_of :name
	validates_format_of :email, with: EMAIL_REGEXP, uniqueness: true
end

app/models/glass.rb
class Glass < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/graphic.rb
class Graphic < ActiveRecord::Base
end

app/models/hardware.rb
class Hardware < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/measure.rb
class Measure < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :type
end

app/models/products_sales.rb
class ProductsSales < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
	belongs_to :categories
	has_and_belongs_to_many :hardwares
	has_and_belongs_to_many :measures
	has_and_belongs_to_many :glasses
	has_and_belongs_to_many :shapes	

	validates_presence_of :title, :code, :category_id
	validates_length_of :description, minimum: 10, maximum: 600, allow_blank: false
end

app/models/sale.rb
class Sale < ActiveRecord::Base
	belongs_to :customer
	belongs_to :user
	has_and_belongs_to_many :product
	validates_presence_of :customer_id, :value, :payment_method
end

app/models/shape.rb
class Shape < ActiveRecord::Base
	has_and_belongs_to_many :projects
end

app/models/state.rb
class State < ActiveRecord::Base
	has_many :cities
end

app/models/type.rb
class Type < ActiveRecord::Base
	has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, stretches: 20
	has_many :sale
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  decorates_assigned :sale
  # GET /sales
  # GET /sales.json
  def index
    sales = Sale.all    
    @sales = sales.map do |sale|
      sale.decorate
    end  
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @payment_methods = [ ["Cartão de crédito", 1], ["Cartão de débito", 2], ["Dinheiro", 3], ["Cheque", 4] ]
    @products = Product.all
  end

  # GET /sales/1/edit
  def edit
    @payment_methods = [ ["Cartão de crédito", 1], ["Cartão de débito", 2], ["Dinheiro", 3], ["Cheque", 4] ]
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render action: 'show', status: :created, location: @sale }
      else
        format.html { render action: 'new' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:customer_id, :user_id, :value, :delivered, :observations, :payment_method, :payed, :product)
    end
end

app/helpers/glasses_helper.rb
module GlassesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sales_helper.rb
module SalesHelper
	def which_method(method)
		case method
		when 1
			return "Cartão de crédito"
		when 2
			return "Cartão de débito"
		when 3
			return "Dinheiro"
		when 4
			return "Cheque"			
		end
	end

	def is_payed(value)
		case value
		when true
			return "Pago!"
		when false
			return "Não pago."
		end
	end

	def is_delivered(value)
		case value
		when true
			return "Entregue!"
		when false
			return "Não entregue."
		end
	end

	def user_name(user)
		if user.present?
			user.name
		end
	end
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/sales/_add_products.html.erb
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12 input-group">
		<label>Buscar produto</label>
		<input type="text" placeholder="Produto..." ng-model="product_add" typeahead="p.title for p in products | filter:$viewValue | limitTo:8" typeahead-on-select="onSelectProduct($item, $model, $label)" typeahead-editable="false" class="form-control">
	</div>
</div>
<br>
<table class="table table-bordered tablestriped">
	<thead>
		<tr>
			<th>Cod.</th>
			<th>Descrição</th>
			<th>Quantidade em estoque</th>
			<th>Valor</th>
			<th>Remover</th>
		</tr>
	</thead>
	<tbody>
		<tr ng-repeat="p in Sale.Product">
			<td>{{p.code}}</td>
			<td>{{p.description}}</td>
			<td>{{p.stock}}</td>
			<td>{{p.value | currency}}</td>
			<td><a ng-click="removeProduct($index)" class="btn btn-xs btn-danger"><i class="glyphicon glyphicon-remove"></i></a></td>
		</tr>
	</tbody>
</table>

app/views/sales/_form.html.erb
<%= bootstrap_form_for(@sale) do |f| %>
  <% if @sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sale.errors.count, "error") %> impediram esta venda de ser realizada</h2>

      <ul>
      <% @sale.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <input type="hidden" name="user_id" ng-model="Sale.user_id" value="1">
  <div class="row">
    <%= link_to "Sign out", new_user_session_path, :method => :post %>
    <div class="col-md-5 col-sm-5 col-xs-12">
      <label class="control-label" for="customer_id">Cliente</label>
      <select name="customer_id" id="customer_id" class="form-control" ng-model="Sale.customer_id" ng-options="c.id as c.name for c in customers">
        <option value="">Selecione</option>
      </select>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-4">
      <label for="payment_method" class="control-label">Forma de pagamento</label>
      <select name="payment_method" id="payment_method" class="form-control" ng-model="Sale.payment_method" ng-options="pm.id as pm.title for pm in payment_methods">
        <option value="">Selecione</option>
      </select>  
    </div>
      <div class="col-md-2 col-sm-2 col-xs-4">
      <br>
        <%= f.check_box :delivered, 'ng-model' => 'Sale.delivered' %>
      </div>
      <div class="col-md-2 col-sm-2 col-xs-4">    
      <br>
        <%= f.check_box :payed, 'ng-model' => 'Sale.payed' %>
      </div>
  </div>
  <div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
      <br>
      <%= f.text_area :observations, 'ng-model' => 'Sale.observations' %>
    </div>
  </div>
  <%= render 'add_products' %>
  <div class="row">
    <h3>Total: {{Sale.value | currency}}</h3>
  </div>
  <div class="row">
    <a ng-click="saveSale()" class="btn btn-primary pull-right">Salvar Venda</a>
  </div>
<% end %>

app/views/sales/edit.html.erb
<h1><%= t('.page_title') %></h1>

<%= render 'form' %>

<%= link_to t('links.view'), @sale %> |
<%= link_to t('links.back'), sales_path %>

app/views/sales/index.html.erb
<h1><%= t('.page_title') %></h1>
<%= link_to t('.new'), new_sale_path, class: 'btn btn-primary pull-right' %>
<br><br>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th><%= t('.customer_id') %></th>
      <th><%= t('.value') %></th>
      <th><%= t('.delivered') %></th>
      <th><%= t('.payment_method') %></th>
      <th><%= t('.payed') %></th>
      <th><%= t('.user') %></th>
      <th><%= t('.observations') %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td><%= sale.customer.name %></td>
        <td><%= number_to_currency(sale.value, unit: "R$ ", separator: ",", delimiter: "") %></td>
        <td><%= sale.delivered? %></td>
        <td><%= sale.payment_method %></td>
        <td><%= sale.payed? %></td>
        <td><%= sale.user_name %></td>
        <td><%= sale.observations %></td>
        <td><%= link_to t('links.view'), sale, class: "btn btn-xs btn-primary" %></td>
        <td><%= link_to t('links.edit'), edit_sale_path(sale), class: "btn btn-xs btn-success" %></td>
        <td><%= link_to t('links.delete'), sale, class: "btn btn-xs btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sales/new.html.erb
<div ng-controller="SaleNewCtrl">
<h1><%= t('.page_title') %></h1>

<%= render 'form' %>
<div class="row">
<p><%= link_to t('links.back'), sales_path %></p>
</div>
</div>

app/views/sales/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @sale.customer_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @sale.user_id %>
</p>

<p>
  <strong>Value:</strong>
  <%= @sale.value %>
</p>

<p>
  <strong>Delivered:</strong>
  <%= @sale.delivered %>
</p>

<p>
  <strong>Observations:</strong>
  <%= @sale.observations %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @sale.payment_method %>
</p>

<p>
  <strong>Payed:</strong>
  <%= @sale.payed %>
</p>

<%= link_to 'Edit', edit_sale_path(@sale) %> |
<%= link_to 'Back', sales_path %>